name: Daily Commit with 21f1004469@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "30 14 * * *"  # Runs daily at 14:30 UTC (adjust to your timezone)
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with 21f1004469@ds.study.iitm.ac.in
        uses: actions/checkout@v4
        
      - name: Create commit with 21f1004469@ds.study.iitm.ac.in
        run: |
          echo "Daily update $(date)" >> daily_log.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "21f1004469@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated daily commit [21f1004469@ds.study.iitm.ac.in]"
          git push
