name: Daily Commit with 21f1004469@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 2:30 PM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits

    steps:
      - name: Checkout code with 21f1004469@ds.study.iitm.ac.in
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full Git history

      - name: Make empty commit with 21f1004469@ds.study.iitm.ac.in
        run: |
          git config --global user.name "Abhimadras"
          git config --global user.email "21f1004469@ds.study.iitm.ac.in"
          git commit --allow-empty -m "Automated daily commit [21f1004469@ds.study.iitm.ac.in]"
          git push
